oauth_register:
    pattern: /oauthRegister
    defaults: { _controller: AcmeMainBundle:Security:oauthRegister }



# app/config/routing.yml
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /tata

# app/config/routing.yml
facebook_login:
    pattern: /tata/check-facebook

google_login:
    pattern: /tata/check-google

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /toto
